### ISSUE TITLE
Please add a TMDB key

### ISSUE THREAD

**Issue by jakesteele** [frenchcutgreenbean/UNIT3D-Upload-Checker#1]
Looking to try out your program here, but I am having an issue. I’ve followed your setup guide, but when I try and run the checker it always asks for a TMDB key. I have tried adding it 5 times with quotes, without quotes etc. 

```
admin@truenas[/mnt/App/Configs/Upload-Checker]$ ./python/bin/python3 ./check.py setting-add -t tmdb -s <REDACTED>
Key is valid and was added to tmdb
admin@truenas[/mnt/App/Configs/Upload-Checker]$ ./python/bin/python3 ./check.py run-all                                                  
Scanning Directories
Searching TMDB
Please add a TMDB key
setting-add -t tmdb -s <key>
```

When I check it, it also says its not set:
`
admin@truenas[/mnt/App/Configs/Upload-Checker]$ ./python/bin/python3 ./check.py setting -t tmdb                                        
Not set yet.
`

I manually set it in the settings.json and that fixed it.

**Comment by frenchcutgreenbean** [comment]
Ahh I had a return after adding a tmdb key, don't know how I missed that. Thank you for the find!

https://github.com/frenchcutgreenbean/UNIT3D-Upload-Checker/commit/0ac180f7b893d1ba21417473033c5f88c35bcd53
